RnD.KendoUISample/Backup/RnD.KendoUISample/Controllers/DemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RnD.KendoUISample.Models;
using RnD.KendoUISample.Helpers;
using RnD.KendoUISample.ViewModels;
using System.Data;

namespace RnD.KendoUISample.Controllers
{
    public class DemoController : Controller
    {
        private AppDbContext _db = new AppDbContext();

        //
        // GET: /Demo/

        public ActionResult Index()
        {
            return View();
        }

        #region CRUD Action For Custom PopUp

        //
        // GET: /Category/Details/By ID

        public ActionResult Details(int id)
        {
            Category category = _db.Categories.Find(id);
            //return View(category);
            return PartialView("_Details", category);
        }

        //
        // GET: /Category/Add

        public ActionResult Add()
        {
            //return View();
            return PartialView("_Add");
        }

        //
        // POST: /Category/Add

        [HttpPost]
        public ActionResult Add(Category category)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _db.Categories.Add(category);
                    _db.SaveChanges();

                    //return RedirectToAction("Index");
                    return Content(Boolean.TrueString);
                }

                //return View(category);
                //return PartialView("_Add", category);
                return Content("Please review your form.");
            }
            catch (Exception ex)
            {
                return Content("Error Occured!");
            }
        }

        //
        // GET: /Category/Edit/By ID

        public ActionResult Edit(int id)
        {
            Category category = _db.Categories.Find(id);

            if (category != null)
            //if (category == null)
            {
                //return View(category);
                return PartialView("_Edit", category);
            }
            else
            {
                return PartialView("_Error");
            }

        }

        //
        // POST: /Category/Edit/By ID

        [HttpPost]
        public ActionResult Edit(Category category)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _db.Entry(category).State = EntityState.Modified;
                    _db.SaveChanges();

                    //return RedirectToAction("Index");
                    return Content(Boolean.TrueString);
                }

                //return View(category);
                //return PartialView("_Edit", category);
                return Content("Please review your form.");
            }
            catch (Exception ex)
            {
                return Content("Error Occured!");
            }
        }

        //
        // GET: /Category/Delete/By ID

        public ActionResult Delete(int id)
        {
            Category category = _db.Categories.Find(id);

            //return View(category);
            return PartialView("_Delete", category);
        }

        //
        // POST: /Category/Delete/By ID

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Category category = _db.Categories.Find(id);
                if (category != null)
                {
                    _db.Categories.Remove(category);
                    _db.SaveChanges();

                    //return RedirectToAction("Index");
                    return Content(Boolean.TrueString);
                }
                return Content("Please review your form.");
            }
            catch (Exception ex)
            {
                return Content("Error Occured!");
            }
        }

        #endregion
    }
}

RnD.KendoUISample/Backup/RnD.KendoUISample/Views/Shared/_Error.cshtml
<div id="errorPage">
    <div class="display-field">
        This is Error!
    </div>
</div>

RnD.KendoUISample/Backup/RnD.KendoUISample/Views/Shared/_JQDialogPartial.cshtml
<script src="@Url.Content("~/Scripts/JQDialog/jqdialog.custom.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/JQDialog/jqdialog.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/JQDialog/jqdialog.min.js")" type="text/javascript"></script>

RnD.KendoUISample/Backup/RnD.KendoUISample/Views/Shared/_KendoPartial.cshtml
<link rel="stylesheet" href="@Url.Content("~/Content/Kendo/kendo.common.min.css")" />
<link rel="stylesheet" href="@Url.Content("~/Content/Kendo/kendo.default.min.css")" />
@*<script src="@Url.Content("~/Scripts/Kendo/jquery.min.js")"></script>*@
<script src="@Url.Content("~/Scripts/Kendo/kendo.web.min.js")"></script>
<script src="@Url.Content("~/Scripts/Kendo/kendo.aspnetmvc.min.js")"></script>

RnD.KendoUISample/Backup/RnD.KendoUISample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/App/app-style.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.8.3.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.24.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
    @*<script src="@Url.Content("~/Scripts/App/app-jq.js")" type="text/javascript"></script>*@
    @Html.Partial("_KendoPartial") @Html.Partial("_JQDialogPartial")
</head>
<body>
    <div class="page">
        <header>
            <div id="title">
                <h1>Kendo UI Sample MVC Application</h1>
            </div>
            <div id="sociallinks">
                @Html.Partial("_SocialLinkPartial")
            </div>
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Category", "Index", "Category")</li>
                    <li>@Html.ActionLink("Product", "Index", "Product")</li>
                    <li>@Html.ActionLink("Upload", "Index", "Upload")</li>
                    <li>@Html.ActionLink("Menu", "Index", "Menu")</li>
                    <li>@Html.ActionLink("Pop Up", "Index", "Demo")</li>
                </ul>
            </nav>
        </header>
        <section id="main">
            <div id="commonMessage" class="common-message"></div>
            @RenderBody()
        </section>
        <footer>
        </footer>
    </div>
</body>
</html>

RnD.KendoUISample/Backup/RnD.KendoUISample/Views/Shared/_SocialLinkPartial.cshtml
<span><a href="https://www.facebook.com/rasel.ahmmed.bappi">
    <img src="../../Content/Images/App/facebook.png" alt="Facebook" /></a></span>
<span><a href="https://twitter.com/raselbappi">
    <img src="../../Content/Images/App/twitter.png" alt="Twitter" /></a></span>
<span><a href="http://bd.linkedin.com/in/raselahmmedbappi">
    <img src="../../Content/Images/App/linkedin.png" alt="Linkedin" /></a></span>